name: Run Consul Pipeline

permissions:
  contents: read
  packages: read
  actions: read

on:
  workflow_dispatch:
    inputs:
      scope:
        description: Test scope
        required: false
        type: choice
        options:
          - pr
          - nightly
        default: pr
      wait_for_dev_build:
        description: Wait for dev_build.yml to complete before tests
        required: false
        type: boolean
        default: false
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"

jobs:
  Wait-for-images:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.wait.outputs.conclusion }}
    steps:
      - name: Wait for dev_build.yml to complete
        if: github.event_name != 'workflow_dispatch' || inputs.wait_for_dev_build == true
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@3e428f45132119ce49d90f3770a45d4fe1d1078d  #v2.0.4
        id: wait
        with:
          workflow: dev_build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          poll-interval: 20
      - name: Skip dev_build wait for manual run
        if: github.event_name == 'workflow_dispatch' && inputs.wait_for_dev_build != true
        run: echo "Skipping dev_build wait for manual run"
  Consul-Pipeline:
    needs: Wait-for-images
    uses: elbe0116/qubership-test-pipelines/.github/workflows/consul.yaml@main
    with:
      repository_name: ${{ github.repository }}
      service_branch: '${{ github.head_ref || github.ref_name }}'
      scope: >-
        ${{ github.event_name == 'workflow_dispatch'
            && github.event.inputs.scope
            || 'pr' }}
      pipeline_branch: 'main'
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
